occupancy_robot_points:
- link_name: "ur5_upper_arm_link"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.05]
  - [0.0, 0.0, 0.1]
  - [0.0, 0.0, 0.15]
  - [0.0, 0.0, 0.2]
  - [0.0, 0.0, 0.25]
  - [0.0, 0.0, 0.3]
  - [0.0, 0.0, 0.35]
  - [0.0, 0.0, 0.4]
- link_name: "ur5_forearm_link"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.05]
  - [0.0, 0.0, 0.1]
  - [0.0, 0.0, 0.15]
  - [0.0, 0.0, 0.2]
  - [0.0, 0.0, 0.25]
  - [0.0, 0.0, 0.3]
  - [0.0, 0.0, 0.35]
  - [0.0, 0.0, 0.4]
- link_name: "ur5_wrist_2_link"
  points:
  - [0.0, 0.0, 0.0]
- link_name: "ur5_wrist_3_link"
  points:
  - [0.0, 0.0, 0.0]
- link_name: "ur5_tool0"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.05]
  - [0.0, 0.0, 0.1]
  - [0.0, 0.0, 0.15]
  - [0.0, 0.0, 0.2]
  - [0.0, 0.0, 0.25]

- link_name: "ur10_upper_arm_link"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.05]
  - [0.0, 0.0, 0.1]
  - [0.0, 0.0, 0.15]
  - [0.0, 0.0, 0.2]
  - [0.0, 0.0, 0.25]
  - [0.0, 0.0, 0.3]
  - [0.0, 0.0, 0.35]
  - [0.0, 0.0, 0.4]
  - [0.0, 0.0, 0.45]
  - [0.0, 0.0, 0.5]
  - [0.0, 0.0, 0.55]
  - [0.0, 0.0, 0.6]
- link_name: "ur10_forearm_link"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.05]
  - [0.0, 0.0, 0.1]
  - [0.0, 0.0, 0.15]
  - [0.0, 0.0, 0.2]
  - [0.0, 0.0, 0.25]
  - [0.0, 0.0, 0.3]
  - [0.0, 0.0, 0.35]
  - [0.0, 0.0, 0.4]
  - [0.0, 0.0, 0.45]
  - [0.0, 0.0, 0.5]
  - [0.0, 0.0, 0.55]
  - [0.0, 0.0, 0.6]
- link_name: "ur10_wrist_1_link"
  points:
  - [0.0, 0.0, 0.0]
- link_name: "ur10_wrist_2_link"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.05, 0.0]
  - [0.0, -0.05, 0.0]
  - [0.05, 0.0, 0.0]
  - [-0.05, 0.0, 0.0]
- link_name: "ur10_wrist_3_link"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.05, 0.0]
  - [0.0, -0.05, 0.0]
  - [0.05, 0.0, 0.0]
  - [-0.05, 0.0, 0.0]
- link_name: "ur10_tool0"
  points:
  - [0.0, 0.0, 0.0]
  - [0.0, 0.0, 0.05]
  - [0.0, 0.0, 0.1]
