# Copyright (c) 2019, Manuel Beschi CNR-STIIMA manuel.beschi@stiima.cnr.it
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
#
#
#
#__  .___  ___. .______     ______   .______     .___________.    ___      .__   __. .___________.
#|  | |   \/   | |   _  \   /  __  \  |   _  \    |           |   /   \     |  \ |  | |           |
#|  | |  \  /  | |  |_)  | |  |  |  | |  |_)  |   `---|  |----`  /  ^  \    |   \|  | `---|  |----`
#|  | |  |\/|  | |   ___/  |  |  |  | |      /        |  |      /  /_\  \   |  . `  |     |  |
#|  | |  |  |  | |  |      |  `--'  | |  |\  \----.   |  |     /  _____  \  |  |\   |     |  |
#|__| |__|  |__| | _|       \______/  | _| `._____|   |__|    /__/     \__\ |__| \__|     |__|
#
# ========================================================================
# THIS IS A TEMPLATE. DON'T MODIFY THIS FILE IN THIS FOLDER.
# COPY IT IN THE [YOUR_CELL]_moveit_config PACKAGE AND THEN
# MODIFY THE PARAMETERS WITH THE COMMENT ***CHANGE IT***
# ========================================================================
group_names_map:
  planner_name: group_name  # one planner_name for each group. ***CHANGE IT***
  
planner_name:
  type: Multigoal
  max_distance: 0.2 # max distance between two edges of the tree. Default value is ok
  max_refine_time: 1.0 # The time duration in seconds that the replanner uses to refine the first solution. A small value produces faster but nonoptimal solutions ***CHANGE IT IF NEEDED***
  extend: false # use RRT-extend instead of RRT-Connect. Default value is ok
  local_bias: 0.25 # sampling bias on the actual solution.  Default value is ok
  tube_radius: 0.02 # tube of the local sampling.  Default value is ok
  use_avoidance_goal: true # set true if the human avoidance is done only at the goal. Useful in Multigoal planning. ***CHANGE IT***
  use_avoidance_path: false # set true if the human avoidance is done during the path. It is slower than use_avoidance_goal. ***CHANGE IT***
  #If use_avoidance_goal and use_avoidance_path are both true, use_avoidance_path is used.

  detector_topic: topic_name #topic name of the message type detector_ros::xyzData. ***CHANGE IT***
  base_frame: world #base_frame of the chain. ***CHANGE IT***
  tool_frame: open_tip #tool_frame of the chain. ***CHANGE IT***

  min_distance: 0.4 # minimum distance between robot and human in meters. if distance<=min_distance the penalty is equal to the max_penalty. Default value is ok
  max_distance: 0.6 # maximum distance  between robot and human in meters. if distance>=max_distance the penalty is 0. Default value is ok
  max_penalty: 10.0 # maximum penalty due to the distance between robot and human. Default value is ok
  display_bubbles: false #display penalty bubbles in rviz on topic "/goal_cost_function/avoidance_points". Default value is ok
  links: # links used for measuring the distance between robot and human. ***CHANGE IT***
  - open_tip
  - tool0
  - wrist_1_link
  - wrist_2_link
  - wrist_3_link
  - forearm_link
  - upper_arm_link


