# Copyright (c) 2019, Manuel Beschi CNR-STIIMA manuel.beschi@stiima.cnr.it
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the <organization> nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
#
#
#
#__  .___  ___. .______     ______   .______     .___________.    ___      .__   __. .___________.
#|  | |   \/   | |   _  \   /  __  \  |   _  \    |           |   /   \     |  \ |  | |           |
#|  | |  \  /  | |  |_)  | |  |  |  | |  |_)  |   `---|  |----`  /  ^  \    |   \|  | `---|  |----`
#|  | |  |\/|  | |   ___/  |  |  |  | |      /        |  |      /  /_\  \   |  . `  |     |  |
#|  | |  |  |  | |  |      |  `--'  | |  |\  \----.   |  |     /  _____  \  |  |\   |     |  |
#|__| |__|  |__| | _|       \______/  | _| `._____|   |__|    /__/     \__\ |__| \__|     |__|
#
# ========================================================================
# THIS IS A TEMPLATE. DON'T MODIFY THIS FILE IN THIS FOLDER.
# COPY IT IN THE [YOUR_CELL]_moveit_config PACKAGE AND THEN
# MODIFY THE PARAMETERS WITH THE COMMENT ***CHANGE IT***
# ========================================================================
group_names_map:
  mixed_strategy: group_name  ***CHANGE IT***
  informed_rrt: group_name  ***CHANGE IT***
  RRTstar: group_name  ***CHANGE IT***
  warp_strategy: group_name  ***CHANGE IT***
  goal_hamp_multigoal:  group_name  ***CHANGE IT***
default_planner_config: mixed_strategy

mixed_strategy:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 2.0
  extend: true
  local_bias: 0.5 # initial probability of local sampling
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.01

warp_strategy:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 2.0
  extend: true
  local_bias: 0.25
  forgetting_factor: 0
  tube_radius: 0.02
  informed: false
  warp: true
  utopia_tolerance: 0.001


RRTstar:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 0.5
  extend: true
  utopia_tolerance: 0.001
  informed: false
  mixed_strategy: false

informed_rrt:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  extend: true
  utopia_tolerance: 0.001

goal_hamp_multigoal:
  type: Multigoal
  max_distance: 0.5
  max_refine_time: 1500.0
  rewire_radius: 2.0
  extend: true
  local_bias: 0.5 # initial probability of local sampling
  forgetting_factor: 0.999
  tube_radius: 0.02
  utopia_tolerance: 0.01

  use_avoidance_goal: true # set true if the human avoidance is done only at the goal. Useful in Multigoal planning. ***CHANGE IT***
  use_avoidance_path: false # set true if the human avoidance is done during the path. It is slower than use_avoidance_goal. ***CHANGE IT***
  #If use_avoidance_goal and use_avoidance_path are both true, use_avoidance_path is used.

  detector_topic: /poses #topic name of the message type geometry_msgs/PoseArray. ***CHANGE IT IF NEEDED***
  base_frame: world #base_frame of the chain. ***CHANGE IT***
  tool_frame: open_tip #tool_frame of the chain. ***CHANGE IT***

  min_distance: 0.4 # minimum distance between robot and human in meters. if distance<=min_distance the penalty is equal to the max_penalty. Default value is ok
  max_distance: 0.6 # maximum distance  between robot and human in meters. if distance>=max_distance the penalty is 0. Default value is ok
  max_penalty: 10.0 # maximum penalty due to the distance between robot and human. Default value is ok
  display_bubbles: false #display penalty bubbles in rviz on topic "/goal_cost_function/avoidance_points". Default value is ok
  links: # links used for measuring the distance between robot and human. ***CHANGE IT***
  - open_tip
  - tool0
  - wrist_1_link
  - wrist_2_link
  - wrist_3_link
  - forearm_link
  - upper_arm_link
