scatola    : {box: [0.05, 0.05, 0.05], color: [1,0.0,0.0,1]}
box    : {box: [0.15, 0.05, 0.05], color: [0.75,0.75,0.75,1]}
big_box_cartesian : {box: [0.4, 0.4, 0.6], color: [0.5,0.5,0.5,1]}
big_box_panda : {box: [0.15, 0.15, 0.8], color: [1,0.0,0.0,1]}
big_box_6dof : {box: [0.2, 0.2, 1.2], color: [1,0.0,0.0,1]}
big_box_sharework: {box: [0.5, 0.5, 0.5], color: [1,0.0,0.0,1]}
big_box_ur10e : {box: [0.1, 0.1, 0.1], color: [1,0.0,0.0,1]}
box_coll_check: {box: [1, 1, 0.1], color: [1,0.0,0.0,1]}
