test_name: "6dof"
group_name: "manipulator"
base_link: "world"
last_link: "flange"
start_configuration: [1.5, 0.5, -0.5, -1.5, -0.7, 0.7]
stop_configuration: [0.0, 0.0, -1.0, 0.0, -1.5, 1.0]
k_freq: 1
init_test: 0
end_test: 200
dt_replan: 0.070
dt_replan_no_obstruction: 0.120
opt_path: true
