group_name: "manipulator"
base_link: "base_link"
last_link: "ee_link"
checker_resolution: 0.05
test: "ur10e"
start_configuration: [0.0,0.0,0.0,0.0,0.0,0.0]
goal_configuration: [2.0,0.0,0.0,0.0,0.0,0.0]

#RESULTS:
#step: 0.01  ur10-> 9-10 ms  ur10e_simplified->2-3 ms  ur10e_robotiq-> 6.5-8 ms OK!
#step: 0.05  ur10-> 2.5-3.5 ms  ur10e_simplified->0.5-0.7 ms  ur10e_robotiq-> 2 ms  OK!

#path length->2.0
