test_name: "sharework"
group_name: "manipulator"
base_link: "base_link"
last_link: "open_tip"
moving_obs: true
disp_verb_informed: false
disp_verb_pathSwitch: false
time_verb: false
time_for_repl: 0.09
opt_path: true
start_configuration: [1.5, 0.0, -0.7, 0.0, 1.5, 0.0]
stop_configuration: [0.5, 0.0, -0.7, 0.0, 1.5, 0.0]
n_test: 1
