test_name: "cartesian"
group_name: "cartesian_arm"
base_link: "world"
last_link: "end_effector"
moving_obs: true
disp_verb_informed: false
disp_verb_pathSwitch: false
time_verb: false
time_for_repl: 0.1
opt_path: true
start_configuration: [0.0, 0.0, 0.0]
stop_configuration: [0.8, 0.8, 0.8]
n_test: 1
