test_name: "ur10e_robotiq"
group_name: "manipulator"
base_link: "base_link"
last_link: "open_tip"
dt_replan_restricted: 0.100
dt_replan_relaxed: 0.150
trj_execution_thread_frequency: 100
collision_checker_thread_frequency: 30
spawn_objs: true
display_timing_warning: true
display_replanning_success: true
scaling: 1.0
checker_resolution: 0.05

start_configuration: [1.0, 0.0, -2.5, -0.5, -1.5, 1.5]
stop_configuration: [0.25, -0.1, -0.7, -2.5, -0.5, 3.0]
init_test: 0
end_test: 10
opt_path: true
