cargo_lower: {mesh: "package://object_loader/example_meshes/CargoPanelLower.stl", scale: [0.5, 0.1, 0.05]}
sidewall   : {mesh: "package://object_loader/example_meshes/SidewallPanel.stl", color: [255,0,0,1]}
scatola    : {box: [0.1, 0.1, 0.1], color: [0.75,0.75,0.75,1]}
