test_name: "panda"
group_name: "panda_arm"
base_link: "panda_link0"
last_link: "panda_link8"
start_configuration: [-0.8, 0.3, 0.0, -2.0, 0.0, 2.5, -0.5]
stop_configuration: [0.8, 0.3, 0.0, -2.0, 0.0, 2.5, -0.5]
k_freq: 1
init_test: 0
end_test: 30
dt_replan: 0.100
dt_replan_no_obstruction: 0.200
optimize_path: 1
