test_name: "cartesian"
group_name: "cartesian_arm"
base_link: "world"
last_link: "end_effector"
start_configuration: [0.0, 0.0, 0.0]
stop_configuration: [0.8, 0.8, 0.8]
k_freq: 1
init_test: 0
end_test: 30
dt_replan: 0.050
dt_replan_no_obstruction: 0.100
opt_path: false
