name: build-manual-deps

on:
  push:
    branches:
      - master
      - devel
      - pull_req
  pull_request:
    branches:
      - master
      - devel
      - pull_req
  schedule:
    - cron: '0 8 * * *'

jobs:
  install-and-run-manual-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Build & Install cnr_common
        run: |
          chmod +x .github/workflows/github_workflow_cnr_common_install.sh 
          .github/workflows/github_workflow_cnr_common_install.sh

      - name: Build & Install graph_core
        run: |
          chmod +x .github/workflows/github_workflow_graph_core_install.sh 
          .github/workflows/github_workflow_graph_core_install.sh
