name: build

on:
  push:
    branches:
      - master
      - devel
      - pull_req
  pull_request:
    branches:
      - master
      - devel
      - pull_req
  schedule:
    - cron: '0 8 * * *'

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Build & Install
        run: |
          mkdir -p src
          mkdir -p build
          mkdir -p install
          export PATH_TO_WS="$(pwd)"

          echo "Workspace Path: $PATH_TO_WS"
          ls -la

          export PATH="$PATH_TO_WS/install/bin:$PATH"
          export LD_LIBRARY_PATH="$PATH_TO_WS/install/lib"
          export CMAKE_PREFIX_PATH="$PATH_TO_WS/install"

          echo "PATH: $PATH"
          echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
          echo "CMAKE_PREFIX_PATH: $CMAKE_PREFIX_PATH"

          mkdir -p build/graph_core
          cmake -S graph_core -B build/graph_core -DCMAKE_INSTALL_PREFIX=$PATH_TO_WS/install
          make -C build/graph_core install