name: build-within-catkin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-and-run-within-catkin:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic

    steps:
      - name: Setup ROS Environment
        shell: bash
        run: |
          echo "Setting up ROS environment"
          source /opt/ros/noetic/setup.bash
          sudo apt update
          sudo apt install -y python3-catkin-tools

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt install -y git libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Build & Install graph_core in Catkin Workspace
        shell: bash
        run: |
          chmod +x .github/workflows/github_workflow_graph_core_install_within_catkin.sh 
          .github/workflows/github_workflow_graph_core_install_within_catkin.sh

      