name: build-within-catkin-vcstool

on:
  push:
    branches:
      - master
      - devel
      - pull_req
  pull_request:
    branches:
      - master
      - devel
      - pull_req
  schedule:
    - cron: '0 8 * * *'

jobs:
  install-and-run-within-catkin:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-catkin-tools libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev python3-vcstools

      - name: Setup Catkin Workspace
        shell: bash
        run: |
          echo "Setting up ROS environment"
          source /opt/ros/noetic/setup.bash

          WORKSPACE_DIR=$(pwd)/graph_core_ws
          SRC_DIR=$WORKSPACE_DIR/src

          echo "WORKSPACE_DIR=$(pwd)/graph_core_ws" >> "$GITHUB_ENV"
          echo "SRC_DIR=$WORKSPACE_DIR/src" >> "$GITHUB_ENV"

          echo "Setting up Catkin workspace at $WORKSPACE_DIR"
          mkdir -p $SRC_DIR
          cd $WORKSPACE_DIR

          catkin init
          catkin config --extend /opt/ros/noetic
          catkin config --install

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: '$SRC_DIR/graph_core'

      - name: Download deps with vcstool
        shell: bash
        run: |
          cd $SRC_DIR
          vcs import < graph_core/deps.repos

      - name: Build & Install graph_core in Catkin Workspace
        shell: bash
        run: |
          cd $WORKSPACE_DIR
          catkin build -cs
          source install/setup.bash