name: build-within-catkin-vcstool

on:
  push:
    branches:
      - master
      - devel
      - pull_req
  pull_request:
    branches:
      - master
      - devel
      - pull_req
  schedule:
    - cron: '0 8 * * *'

jobs:
  install-and-run-within-catkin:
    runs-on: ubuntu-20.04
    container:
      image: ros:noetic

    steps:
      - name: Setup ROS Environment
        shell: bash
        run: |
          echo "Setting up ROS environment"
          source /opt/ros/noetic/setup.bash
          sudo apt update
          sudo apt install -y python3-catkin-tools

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt update
          sudo apt install -y git libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev python3-vcstool

      - name: Build & Install graph_core in Catkin Workspace
        shell: bash
        run: |
          # Ensure the setup script is executable
          chmod +x .github/workflows/github_workflow_graph_core_install_within_catkin.sh 
          # Run the installation script
          .github/workflows/github_workflow_graph_core_install_within_catkin.sh
