name: Build and Install graph_core

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  install-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ubuntu
        run: |
          sudo apt-get update
          sudo apt install libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Build & Install cnr_common
        run: |
          chmod +x .github/workflows/github_workflow_cnr_common_install.sh 
          .github/workflows/github_workflow_cnr_common_install.sh

      - name: Build & Install graph_core
        run: |
          chmod +x .github/workflows/github_workflow_graph_core_install.sh 
          .github/workflows/github_workflow_graph_core_install.sh
      

