name: run gtests

on:
  workflow_run:
    workflows: ["build"] # Nome del workflow precedente
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace-artifact
          path: workspace

      - name: Install runtime dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Run GTESTS
        run: |
          cd install/bin/graph_core/tests
          ./run_all_tests
