name: run gtests

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ubuntu_version: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
      fail-fast: true

    steps:
      - name: Download workspace artifact
        uses: actions/download-artifact@v4
        with:
          name: workspace-artifact-${{ matrix.ubuntu_version }}
          path: workspace

      - name: Install runtime dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-all-dev libeigen3-dev libyaml-cpp-dev libpoco-dev liblog4cxx-dev libgtest-dev

      - name: Run GTESTS
        run: |
          cd workspace/install/bin/graph_core/tests
          ./run_all_tests
